server:
  host: localhost
  port: 8888
db:
  dbname: "postgres"
  host: "postgres"
  user: "postgres" 
  password: "postgres" 
  port: 5432
  sslmode: disable 
logger:
  file:
redis:
  url: "redis:6379"